---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - memcached_v1alpha1_memcached.yaml
  - memcached_v1alpha1_minimal.yaml
  - memcached_v1alpha1_ha.yaml
  - memcached_v1alpha1_monitoring.yaml
  - memcached_v1alpha1_tls.yaml
  - memcached_v1alpha1_production.yaml
  - memcached_v1alpha1_autoscaling.yaml
