apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../rbac
patches:
  - path: role_patch.yaml
    target:
      kind: ClusterRole
      name: manager-role
  - target:
      kind: ClusterRoleBinding
      name: manager-rolebinding
    patch: |-
      - op: replace
        path: /kind
        value: RoleBinding
      - op: replace
        path: /roleRef/kind
        value: Role
